title: Kynetic Intelligence
email: info@kynetic.ai
description: >-
  One brain. Any robot.
baseurl: ""
url: "https://kynetic.ai"
github_username: kynetic-ai
theme: minima
show_excerpts: true
header_pages:
  - blog.markdown
  - company.markdown
  - research.markdown
  - team.markdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
