# Site settings
title: kynetic intelligence
email: hello@kynetic.ai
description: "One brain. Any robot."
baseurl: ""
url: "https://kynetic.ai"
github_username: kynetic-ai
linkedin_username: kynetic-intelligence

# Navigation
header_pages:
  - blog.md
  - about.markdown

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
